name: dotnet package

on:
  push:
    branches: [ main ]
  create:
      tags:
        - v*

jobs:

  # build_run_linux_sp:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: make
  #     run: make FOO=-fno-stack-protector
  #   - name: run
  #     run: ./main

  upload-release:

    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: Kompilat
    - name: Zip artifacts
      run: zip ConsoleUtils.zip ./* -r
    - name: Display structure of downloaded files
      run: ls -R
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: | 
            ConsoleUtils.zip
            VERSION

  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.0.x'
      - name: Make dir
        run: mkdir bin
      - name: Install dependencies
        run: dotnet restore
        working-directory: ./ConsoleUtils
      - name: Install NuGet dependencies
        run: nuget restore ConsoleUtils.sln
        working-directory: ./ConsoleUtils
      - name: Build
        run: dotnet build --configuration Release --no-restore --output ../bin -p:Platform=x64
        working-directory: ./ConsoleUtils
      - name: Show Builddir
        run: ls ./bin
      - name: Create Version File
        run: git describe --tags > ./bin/VERSION
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Kompilat
          path: bin
          retention-days: 7
